export const enum NODE_TYPE {
  INTERPOLATION = 'INTERPOLATION',
  SIMPLE_EXPRESSION = 'SIMPLE_EXPRESSION',
  ELEMENT = "ELEMENT",
  TEXT = "TEXT",
  ROOT = "ROOT",
  COMPOUND_EXPRESSION = "COMPOUND_EXPRESSION"
}